version: '3'
services:
  # Processing
  processor:
    build: ./processing
    restart: "no"
    depends_on:
      - db
    volumes:
      - ./import:/import
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somethingrandom
      POSTGRES_DB: imports
      THREADS: 500
      MAXRECORDS: 50000

  # Database
  db:
    image: postgres:11
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somethingrandom
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: imports

  # Example viwer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
